# Generated by Django 6.0.3 on 2026-03-05 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('document_submitted', 'Document Submitted'), ('face_verification_pending', 'Face Verification Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('signed', 'Signed')], default='initiated', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_kycs', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_kycs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='kyc_kycveri_status_df6c85_idx'), models.Index(fields=['partner'], name='kyc_kycveri_partner_3ff63b_idx'), models.Index(fields=['created_at'], name='kyc_kycveri_created_977621_idx')],
            },
        ),
    ]
