# Generated by Django 6.0.3 on 2026-03-05 01:02

import apps.kyc.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.kyc.models.document_upload_path)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycverification')),
            ],
        ),
    ]
