# Generated by Django 6.0.3 on 2026-03-05 01:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_identitydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_verification', to='kyc.kycverification')),
            ],
        ),
    ]
