# Generated by Django 6.0.3 on 2026-03-05 01:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_faceverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_value', models.TextField()),
                ('public_key_fingerprint', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='kyc.kycverification')),
            ],
        ),
    ]
